font_family     Fira Code SemiBold
font_features   FiraCode-SemiBold +ss01 +ss02 +ss03 +ss05 +cv01
font_size 	    13.0
bold_font        	auto
italic_font      	auto
bold_italic_font 	auto

enabled_layouts *
allow_remote_control yes

confirm_os_window_close 0

foreground         #E9E7FD
background         #231B28
background_opacity 0.7
cursor             #A798C7

selection_foreground #00ecff
selection_background #F5FBFF

active_tab_foreground     #231B28
active_tab_background     #E9E7FD
inactive_tab_foreground   #E9E7FD
inactive_tab_background   #231B28

active_border_color   #E9E7FD
inactive_border_color #231B28
bell_border_color     #C1BAFA

color0    #4A4150
color1		#290C46
color2		#8976BB
color3		#67598D
color4		#00ecff
color5		#8A83B4
color6		#918CBC
color7		#D8D4F4
color8		#B8AFF0
color9		#36105D
color10		#644992
color11		#B8AFF0
color12		#8976BB
color13		#B8AFF0
color14		#C1BAFA
color15		#D8D4F4
shell fish
