$background = rgb(231B28)
$foreground = rgb(E9E7FD)
$color0 = rgb(4A4150)
$color1 = rgb(290C46)
$color2 = rgb(4B376D)
$color3 = rgb(8E0D3C)
$color4 = rgb(67598D)
$color5 = rgb(8A83B4)
$color6 = rgb(918CBC)
$color7 = rgb(D8D4F4)
$color8 = rgb(9794AB)
$color9 = rgb(36105D)
$color10 = rgb(644992)
$color11 = rgb(BD1150)
$color12 = rgb(8976BB)
$color13 = rgb(B8AFF0)
$color14 = rgb(C1BAFA)
$color15 = rgb(D8D4F4)
