# game tags
windowrule = match:class ^(gamescope)$, tag +games
windowrule = match:class ^(steam_app_\\d+)$, tag +games
windowrule = match:title .*\.exe, tag +games

# gamestore tags
windowrule = match:class ^([Ss]team)$, tag +gamestore
windowrule = match:title ^([Ll]utris)$, tag +gamestore
windowrule = match:class ^(com.heroicgameslauncher.hgl)$, tag +gamestore

# === Règles fenêtres Steam et autres jeux ===
windowrule {
    name = steam
    match:class = ^([Ss]team)$
    tile = on
    workspace = 9 silent
}

windowrule = match:tag gamestore match:title negative:^([Ss]team)$, float on

windowrule {
    name = steam-float
    match:title = ^(L.*|Para.*|A.*)
    workspace = 9 silent
    float = on
    move = 60% 50%
    size = 40% 40%
}

windowrule {
  name = idle-inhibit-steam
  match:class = ^(steam_app_).*
  workspace = 1
  content = game
  center = on
  immediate = on
  no_blur = on
  idle_inhibit = focus
}

# === Règle pour MTGA ===
windowrule {
  name = mtga-steam
  match:title = ^(MTGA).*
  workspace = 1
  content = game
  no_blur = on
  maximize = on
}
# === Règle pour Dofus ===
windowrule {
  name = dofus
  match:class = ^(Dofus.x64)$
  workspace = 1
  float = on
  immediate = on
  size = 3438 1390
  move = 1 43
}

