require("configs lua/Animations")
require("configs lua/Keybinds")
require("configs lua/ENVariables")
require("configs lua/Animations")
require("configs lua/Decorations")
require("configs lua/Keybinds_app")
require("configs lua/Monitors")
require("configs lua/Settings")
require("configs lua/Startup_Apps")
require("configs lua/WindowRules")
require("configs lua/WindowRulesGaming")

