[spotipy]
client_id = da53f27c966d4d309baa4b2520e5abfa
client_secret = c816e5d6049147089cadee10669031b3
redirect_uri = http://localhost:8080

[spotify]
spotify_username = Eaquo

[settings]
show_playback_popups = ture
show_add_to_playlist_popups = true
track_search_max_entries = 5

